### ISSUE TITLE
Could be a bug?

### ISSUE THREAD

**Issue by leexinhao** [Beckschen/LLaVolta#3]
![image](https://github.com/user-attachments/assets/9f1af5f2-a22e-4b90-b585-08cecb33bc04)
I think this should be `image_idx[0]`? Because it is a tuple of length 1, otherwise it will be out of bounds

**Comment by Beckschen** [comment]
Hi Xinhao,

Thank you for your interest. The current version supports only one image per input. This bug occurs when multiple images are provided, which is rare in the LLaVA training data. 

We have fixed the issue and updated the codebase. Would you please take a look? Thanks again! 😊

Best
Jieneng

**Comment by leexinhao** [comment]
Thanks!
